import styles from '@/styles/Home.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import type { ReactElement } from 'react'

import CatCard from '@/components/cards/cat/CatCard'
import { mockCatCardProps } from '@/components/cards/cat/CatCard.mocks'
import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout'
import SideBarLayout from '@/components/layouts/sidebar/SideBarLayout'
import { NextPageWithLayout } from './_app'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.grid}>
          <CatCard {...mockCatCardProps.base} />
          <CatCard {...mockCatCardProps.base} />
          <CatCard {...mockCatCardProps.base} />
          <CatCard {...mockCatCardProps.base} />
        </section>
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <PrimaryLayout>
      <SideBarLayout>{page}</SideBarLayout>
    </PrimaryLayout>
  )
}

export default Home
